### PR TITLE
Quiet a warning when CONNEXTDDS_DIR or NDDSHOME is not found.

### PR DESCRIPTION
**Pull request by clalancette**
Failing to find those is an acceptable situation; in that case, we will end up just not building rmw_connextdds. Quiet the warning to only a STATUS message so it doesn't cause builds to go yellow.

I found this while trying to run CI for https://github.com/ros2/ci/pull/789, where the RHEL build goes yellow if we don't install Connext.

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by clalancette** [comment]
Pulls: ros2/rmw_connextdds#158
Gist: https://gist.githubusercontent.com/clalancette/938f8071e218482c547728874df7f1d2/raw/b40064e0e3bde770181d528b486161b5c0ed38a8/ros2.repos
BUILD args:  --packages-above-and-dependencies rti_connext_dds_cmake_module
TEST args:  --packages-above rti_connext_dds_cmake_module
ROS Distro: rolling
Job: ci_launcher
ci_launcher ran: https://ci.ros2.org/job/ci_launcher/14435
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21703/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15977/)
* Linux-rhel [Build Status](http://ci.ros2.org/job/ci_linux-rhel/1208/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/22407/)

**Comment by clalancette** [comment]
Aarch64 is meant to fail, since we don't currently support Connext there.  There is one failing test on Linux-rhel, but that is also expected right now (and happens on the nightlies).  So going ahead and merging this one.

**Comment by clalancette** [comment]
@mergifyio backport jazzy

**Comment by clalancette** [comment]
@Mergifyio backport humble

**Pull request merged**
